### ISSUE TITLE
I'm really looking forward to your source code 

### ISSUE THREAD

**Issue by yangzhou321** [KimiaLabMayo/PathDino#1]
Hi ! I recently came across your work on arxiv, and I must say the results are really impressive! I'm very interested in the implementation process of FPS (Fast Patch Selection). I hope you consider opening the source code soon, even releasing pre-trained weights and inference code would be appreciated.

**Comment by saghiralfasly** [comment]
@yangzhou321 Sorry for the late reply. Today, we release our codebase and the pretrained PathDino model.

**Comment by afilt** [comment]
Hello @saghiralfasly, if I understand you correctly, you plan to release the model's weights today so that to re-use the feature extraction code calling `'./inference/PathDino512.pth'` ? Thanks.

**Comment by saghiralfasly** [comment]
Hi @yangzhou321 you can find the PathDino's weights in the huggingFace repo: https://huggingface.co/spaces/Saghir/PathDino/tree/main

**Comment by alabgh01** [comment]
Marking this issue as resolved and closing.
