### ISSUE TITLE
About the preprocessing patching code

### ISSUE THREAD

**Issue by Elliot-QxZhang** [KimiaLabMayo/PathDino#4]
Hi! Thanks for your excellent work. However, I could not find the preprocess codes for generating the patches from WSIs, could you share them?

**Comment by saghiralfasly** [comment]
Hi @Elliot-QxZhang, please find the preprocessing code (the patching code and the used TCGA WSI list): https://github.com/KimiaLabMayo/PathDino/tree/main/preprocessing
