### ISSUE TITLE
Data set link - Page not Found

### ISSUE THREAD

**Issue by Ceachi** [KimiaLabMayo/PathDino#5]
The provided link to the dataset is no longer available:
[(TCGA Diagnositc WSI List).](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.program.name%22%2C%22value%22%3A%5B%22TCGA%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.access%22%2C%22value%22%3A%5B%22open%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_format%22%2C%22value%22%3A%5B%22svs%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%5D%7D%7D%5D%7D) 

![image](https://github.com/KimiaLabMayo/PathDino/assets/22774586/494c94e7-4087-48bb-ae69-a3370ae0b9a8)

Can you please provide the link so I can download the .svs images used in your study?

**Comment by saghiralfasly** [comment]
Hi @Ceachi, please find the list of the used WSIs here:
https://github.com/KimiaLabMayo/PathDino/tree/main/preprocessing
